### PR TITLE
WIP: Add support for iOS and Bluetooth printing

### PR DESCRIPTION
**Pull request by Ayiga**
I'm opening this primarily for discussion and so you can see the differences that I have brought upon the plugin in getting it to work for our needs.

I would also like to double check and verify that I'm not clobbering your original functionality in any way, because that might be a bit of a step back.

The majority of the added code and files comes from Brother's example projects themselves, and as such, there may be some unnecessary additions.  The files were copied *as is*, and I only modified a few of them to suit my purposes.

There are currently some issues with iOS and bluetooth.  Specifically, iOS requires a modal popup for selecting or pairing with a bluetooth printer.  This modal popup, seemingly, is inconsistent at best.  Half the time selecting the printer doesn't seem to do anything.  Due to the issues I have encountered with iOS, as well as the workflow for selecting the printer being different, I have disabled the iOS bluetooth printing aspects.

These additions have removed some of the hard-coding that existed in the project.  As such, methods like `findNetworkPrinters` now returns a list of objects specifying the Discovered Printers.  You now have to manually set the printer by calling `setPrinter` and providing one of the printers returned from `findNetworkPrinters`, `findPrinters`, or `findBluetoothPrinters`.

## Changes Overview
* Add Bluetooth support for Android
* Add Library support for iOS
* Change `findNetworkPrinters` to return a list of Discovered Printers
* Add the ability to specify which printer to print to with `setPrinter`
* Add saved preferences on calls to `setPrinter` (This means that last printer selected will be saved into user preferences for the App itself, and will not need to be reset on launch, unless the address or something changes.)
* Modify callback behavior of `printViaSDK` to return after success or failure.
* Update version to 0.0.4
* Rename plugin from `com.threescreens.cordova.plugin.brotherPrinter` to `cordova-brother-label-printer`
* Add `package.json` file to support newer cordova plugin syntax.

## TODO
* Label size is currently hard-coded and specified on calls to `setPrinter`
* The `supported` printer list only contains printers I have tested personally, `Brother QL-720NW` and `Brother QL-820NWB`.  With changes to allow for the changing of the label type, this would likely support all brother label printers, but it needs to be tested by someone with access.

## Out of Scope
* Print queue.  Brother Label Printers can only accept a single connection at a time, and as such can only print one job at a time.  A simple print queue can be made with Promises, but that's for the end user to implement.

### CODE REVIEW

**Comment by dev-fJ-del** [comment]
@Ayiga this is some very good stuff! well done.
I don't know if @gordol will respond in time for the pull request, I've also forked a copy of this project and would like to know if you maybe can drop a pull request on my copy please? I'm busy with a warehouse scanning app and can do with this code!
Thanks and keep up the good work

**Comment by gordol** [comment]
niiiiiiceee. give me a bit to review, please. this is great stuff though, thanks!

> methods like findNetworkPrinters now returns a list of objects specifying the Discovered Printers. You now have to manually set the printer by calling setPrinter and providing one of the printers returned from findNetworkPrinters, findPrinters, or findBluetoothPrinters.

Heh, that's pretty much how I actually had it originally when I hacked this together for an MVP that required it. I just pushed an array of printers through Cordova to JS and showed a list to choose from. However, the client asked us to hard-code the printer because we were deploying a bunch of these label printers along w/ an Android device to a bunch of end users. It was deemed too annoying to have them pick, so I just hard coded it. <_<

> Print queue. Brother Label Printers can only accept a single connection at a time, and as such can only print one job at a time. A simple print queue can be made with Promises, but that's for the end user to implement.

Indeed! This can be an issue, depending on your deployment. It wasn't an issue for the project I did when I first created this, because we deployed the printer and device that prints along with a portable hotspot, and our device was the only device on the network with the printer, and our app only allowed one print at a time, in serial, as the printing was part of a user workflow.

**Comment by gordol** [comment]
@Ayiga can you please document the new plugin methods in the readme?

**Comment by gordol** [comment]
I changed the merge base to dev... going to accept this as-is, but let's get the readme up to date, and do some testing!

**Comment by gordol** [comment]
i put some placeholders in the readme for the docs...

**Comment by arcadius** [comment]
@Ayiga This is looking really good :+1: .
Excellent work!  :1st_place_medal:

**Pull request merged**
